FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04 AS base

FROM mambaorg/micromamba:latest AS conda

USER root

RUN micromamba install -y --prefix /opt/conda -c bioconda -c conda-forge \
    bcftools=1.14 samtools=1.14 htslib=1.14 minimap2=2.17 && \
    micromamba clean -aqy


FROM base AS builder

ARG DEBIAN_FRONTEND="noninteractive"

RUN \
    apt-get update \
    && apt-get install -yq --no-install-recommends \
    ca-certificates build-essential cmake curl wget git \
    zlib1g-dev libbz2-dev liblzma-dev libncurses5-dev libcurl4-gnutls-dev \
    libssl-dev libffi-dev \
    libreadline8 libreadline-dev sqlite3 libsqlite3-dev file \
    python3-all-dev python3-venv python3-pip python3-setuptools \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 10

ENV VIRTUAL_ENV=/venv

COPY requirements.txt /tmp/requirements.txt
RUN --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
    uv venv ${VIRTUAL_ENV} && \
    uv pip install --no-cache -r /tmp/requirements.txt


FROM base AS runtime

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="Medaka (https://github.com/nanoporetech/medaka)"
LABEL org.opencontainers.image.source="https://github.com/dialvarezs/containers"

RUN \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y libreadline8 sqlite3 python3 procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

COPY --from=builder /venv /venv
COPY --from=conda /opt/conda /opt/conda

ENV PATH=/venv:/opt/conda/bin/:$PATH
