FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04 as base

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="Medaka (https://github.com/nanoporetech/medaka)"
LABEL org.opencontainers.image.source=https://github.com/dialvarezs/containers


FROM mambaorg/micromamba:latest as conda

USER root

RUN micromamba install -y bcftools=1.11 samtools=1.11 htslib=1.11 minimap2=2.11 && \
	micromamba clean -aqy


FROM base as builder

ENV DEBIAN_FRONTEND=noninteractive

RUN \
	apt-get update \
	&& apt-get install -yq --no-install-recommends \
        ca-certificates build-essential cmake curl wget git \
        zlib1g-dev libbz2-dev liblzma-dev libncurses5-dev libcurl4-gnutls-dev \
        libssl-dev libffi-dev \
        libreadline8 libreadline-dev sqlite3 libsqlite3-dev file \
        python3-all-dev python3-venv python3-pip python3-setuptools \
	&& update-alternatives --install /usr/bin/python python /usr/bin/python3 10 \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt


FROM base as runtime

RUN \
	apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y libreadline8 sqlite3 python3 python3-setuptools procps && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

COPY --from=builder /usr/local /usr/local
COPY --from=conda /opt/conda /opt/conda


ENV PATH=/opt/conda/bin/:$PATH