FROM mambaorg/micromamba:latest as build

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="CheckM2 (https://github.com/chklovski/CheckM2)"
LABEL org.opencontainers.image.source=https://github.com/dialvarezs/containers

USER root

RUN apt-get update && \
    apt-get install -y git && \
    rm -fr /var/lib/apt/lists/*

COPY VERSION /tmp/VERSION

RUN git clone https://github.com/chklovski/CheckM2 /tmp/checkm2 && \
	git -C /tmp/checkm2 checkout $(cat /tmp/VERSION)
# install deps
RUN micromamba install -y -n base -f /tmp/checkm2/checkm2.yml && \
	micromamba clean -aqy

# install CheckM2
RUN /opt/conda/bin/pip install /tmp/checkm2



FROM mambaorg/micromamba:latest as final

USER root

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

COPY --from=build /opt/conda /opt/conda

ENV PATH=/opt/conda/bin/:$PATH