FROM python:3.11-slim

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="polars (https://github.com/pola-rs/polars)"
LABEL org.opencontainers.image.source=https://github.com/dialvarezs/containers


RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
