FROM mambaorg/micromamba:latest

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="Abricate (https://github.com/tseemann/abricate) with fixed Megares download"
LABEL org.opencontainers.image.source="https://github.com/dialvarezs/containers"

USER root

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y wget procps && \
    rm -fr /var/lib/apt/lists/*

COPY VERSION /tmp/VERSION

# install abricate from bioconda
RUN micromamba install -y -n base -c bioconda -c conda-forge abricate=$(cat /tmp/VERSION) && \
    micromamba clean -aqy

# download fixed abricate-get_db
RUN wget https://raw.githubusercontent.com/dialvarezs/abricate/master/bin/abricate-get_db -O /opt/conda/bin/abricate-get_db && \
    chmod +x /opt/conda/bin/abricate-get_db


ENV PATH=/opt/conda/bin/:$PATH
