FROM python:3.9-slim

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="csvkit (https://github.com/wireservice/csvkit)"
LABEL org.opencontainers.image.source https://github.com/dialvarezs/containers


RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt