FROM python:3.10-slim

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="scikit-learn (https://scikit-learn.org) plus joblib (https://joblib.readthedocs.io/en/latest/)"
LABEL org.opencontainers.image.source https://github.com/dialvarezs/containers


RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt