FROM mambaorg/micromamba:latest

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="dRep (https://github.com/MrOlm/drep) and dependencies"
LABEL org.opencontainers.image.source https://github.com/dialvarezs/containers

USER root

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

# install dRep dependencies
COPY env.yaml /tmp/env.yaml

RUN micromamba install -y -f /tmp/env.yaml && \
    micromamba clean -aqy

# install dRep
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/pip install --no-cache-dir -r /tmp/requirements.txt

ENV PATH=/opt/conda/bin/:$PATH

# test
RUN dRep check_dependencies