FROM python:3.12-slim

ARG DEBIAN_FRONTEND="noninteractive"

LABEL author="Diego Alvarez (dialvarezs@gmail.com)"
LABEL description="MultiQC (https://github.com/MultiQC/MultiQC) with nanoq patched module"
LABEL org.opencontainers.image.source="https://github.com/dialvarezs/containers"

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y procps && \
    rm -fr /var/lib/apt/lists/*

ENV VIRTUAL_ENV=/venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

COPY requirements.txt /tmp/requirements.txt
RUN --mount=from=ghcr.io/astral-sh/uv:latest,source=/uv,target=/bin/uv \
    uv venv ${VIRTUAL_ENV} && \
    uv pip install --no-cache -r /tmp/requirements.txt

# "patch" nanoq module ot use bar chart instead of line chart
COPY nanoq.py /venv/lib/python3.12/site-packages/multiqc/modules/nanoq/nanoq.py
