name: publish Entrez Direct to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "edirect/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: edirect
      registry: ghcr.io
      image: ${{ github.repository }}/edirect
      directory: ./edirect/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
