name: publish Abricate to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "abricate/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: abricate
      image: ${{ github.repository }}/abricate
      directory: ./abricate/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
