name: dRep to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "drep/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_pypkg.yml
    with:
      package_name: drep
      image: ${{ github.repository }}/drep
      directory: ./drep/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}