name: publish antiSMASH to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "antismash-lite/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: antismash-lite
      image: ${{ github.repository }}/antismash-lite
      directory: ./antismash-lite/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
