name: MultiQC to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "multiqc/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_pypkg.yml
    with:
      package_name: multiqc
      image: ${{ github.repository }}/multiqc
      directory: ./multiqc/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
