name: dRep to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "drep/*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}/drep
  DIRECTORY: ./drep/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version
        id: getversion
        run: echo "::set-output name=version::$(cat ./drep/requirements.txt | grep -Po '(?<=drep==)[0-9.]+')"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DIRECTORY }}
          file: ${{ env.DIRECTORY }}/Containerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.getversion.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}