name: publish qsv to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "qsv/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: qsv
      image: ${{ github.repository }}/qsv
      directory: ./qsv/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}