name: utils to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "utils/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: utils
      registry: ghcr.io
      image: ${{ github.repository }}/utils
      directory: ./utils/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
