name: dorado to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "dorado/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_generic.yml
    with:
      name: dorado
      registry: ghcr.io
      image: ${{ github.repository }}/dorado
      directory: ./dorado/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}