name: csvkit to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "csvkit/*"
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_publish_pypkg.yml
    with:
      package_name: csvkit
      image: ${{ github.repository }}/csvkit
      directory: ./csvkit/
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
