name: publish CheckM2 to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "checkm2/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log into Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version
        id: getversion
        run: |
          VERSION=$(cat checkm2/VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: checkm2
          file: checkm2/Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/checkm2:${{ steps.getversion.outputs.version }}
            ghcr.io/${{ github.repository }}/checkm2:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}