name: Reusable Workflow for Publish python packages to GitHub Container Registry

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      directory:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log into Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version
        id: getversion
        run: |
          PACKAGE=${{ inputs.package_name }}
          DIRECTORY=${{ inputs.directory }}
          VERSION=$(cat ./${DIRECTORY}/requirements.txt | grep -Po "(?<=${PACKAGE}==)[0-9.]+")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.directory }}
          file: ${{ inputs.directory }}/Containerfile
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image }}:${{ steps.getversion.outputs.version }}
            ${{ inputs.registry }}/${{ inputs.image }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
