name: Reusable Workflow for Publish tools to GitHub Container Registry

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
      image:
        required: true
        type: string
      directory:
        required: true
        type: string
      date_as_version:
        required: false
        type: boolean
        default: false
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log into Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        if: ${{ !inputs.date_as_version }}
        run: |
          TOOL=${{ inputs.name }}
          DIRECTORY=${{ inputs.directory }}
          echo "tag=$(cat ./${DIRECTORY}/VERSION)" >> $GITHUB_ENV

      - name: Get date as version
        id: get_version_date
        if: ${{ inputs.date_as_version }} 
        run: |
          DATE=$(date +'%Y%m%d')
          echo "tag=$DATE" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.directory }}
          file: ${{ inputs.directory }}/Containerfile
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image }}:${{ env.tag }}
            ${{ inputs.registry }}/${{ inputs.image }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
